---
- name: Install Redis
  become: true
  ansible.builtin.apt:
    name: redis-server
    state: present

- name: Ensure Redis is started and enabled
  become: true
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: true

- name: Configure Redis to allow external connections
  become: true
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind\s+.*'
    line: "bind 0.0.0.0"
    state: present
  notify: Restart Redis
