---
all:
  children:
    gce_compute:
      hosts:
        gce.kentaro1043.com:
          ansible_user: kentaro
          ansible_python_interpreter: /usr/bin/python3
    oci_compute:
      hosts:
        oci.kentaro1043.com:
          ansible_user: kentaro
          ansible_ssh_user: ubuntu
          ansible_python_interpreter: /usr/bin/python3
