- name: Ensure /swapfile exists at desired size
  become: true
  community.general.filesize:
    path: "/swapfile"
    size: "{{ swap_size }}"
    owner: root
    group: root
    mode: "0600"

- name: Format /swapfile as swap
  become: true
  community.general.filesystem:
    fstype: swap
    dev: /swapfile

- name: Enable swap on /swapfile
  become: true
  ansible.builtin.command:
    cmd: swapon /swapfile
  when: ansible_swaptotal_mb < 1
  changed_when: true

- name: Ensure swap is enabled and persistent in fstab
  become: true
  ansible.posix.mount:
    src: /swapfile
    path: none
    fstype: swap
    opts: sw
    dump: 0
    passno: 0
    state: present
