# NOTE: swaponにおけるファイルサイズのフォーマットと、swap_sizeに設定した値のフォーマットが一致することを確認する必要あり
# swaponにおいては1Gが1024Mとして表示される？

- name: Check swap status
  ansible.builtin.command:
    cmd: swapon --show=NAME,SIZE
  register: swap_status
  changed_when: false

- name: Extract current /swapfile size from swapon output (if present)
  ansible.builtin.set_fact:
    current_swapfile_size: "{{ (swap_status.stdout | regex_search('(?m)^/swapfile\\s+\\S+') | default('')) | regex_replace('^/swapfile\\s+', '') }}"
  when: swap_status.stdout is defined
  changed_when: false

- name: Disable swap if it is already enabled and not matching desired size
  become: true
  ansible.builtin.command:
    cmd: swapoff /swapfile
  when: current_swapfile_size != "" and current_swapfile_size != swap_size
  register: swap_disable
  changed_when: true

- name: Ensure /swapfile exists at desired size
  become: true
  community.general.filesize:
    path: "/swapfile"
    size: "{{ swap_size }}"
    owner: root
    group: root
    mode: "0600"
  notify:
    - Make file as swap

- name: Flush handler to ensure swapfile is ready
  ansible.builtin.meta: flush_handlers

- name: Enable swap on /swapfile
  become: true
  ansible.builtin.command:
    cmd: swapon /swapfile
  when: current_swapfile_size == "" or (swap_disable is defined and swap_disable.changed)
  changed_when: true

- name: Ensure swap is enabled and persistent in fstab
  become: true
  ansible.posix.mount:
    src: /swapfile
    path: none
    fstype: swap
    opts: sw
    dump: 0
    passno: 0
    state: present
