# NOTE: swaponにおけるファイルサイズのフォーマットと、swap_sizeに設定した値のフォーマットが一致することを確認する必要あり
# swaponにおいては1Gが1024Mとして表示される？

- name: Check swap status
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      swapon --show=NAME,SIZE | grep -oP '^/swapfile\s+\K[\d.]+[A-Z]'
    executable: /bin/bash
  register: current_swapfile_size
  changed_when: false
  ignore_errors: true

- name: Disable swap if it is already enabled and not matching desired size
  become: true
  ansible.builtin.command:
    cmd: swapoff /swapfile
  when: current_swapfile_size.stdout != "" and current_swapfile_size.stdout != swap_size
  register: swap_disable
  changed_when: true

- name: Ensure /swapfile exists at desired size
  become: true
  community.general.filesize:
    path: "/swapfile"
    size: "{{ swap_size }}"
    owner: root
    group: root
    mode: "0600"
  notify:
    - Make file as swap

- name: Flush handler to ensure swapfile is ready
  ansible.builtin.meta: flush_handlers

- name: Ensure swap is enabled and persistent in fstab
  become: true
  ansible.posix.mount:
    src: /swapfile
    path: none
    fstype: swap
    opts: sw
    dump: 0
    passno: 0
    state: present

- name: Enable swap on /swapfile
  become: true
  ansible.builtin.command:
    cmd: swapon /swapfile
  when: current_swapfile_size.stdout == "" or (swap_disable is defined and swap_disable.changed)
  changed_when: true
