secret_kubelet_provider_id_okenode1: ENC[AES256_GCM,data:Jex0B26mO65/yKrRPVlF+XM7gLzjXmdjCsb/PfBP/aGjSVVI2Crk7L9VwoHqvWCYx0unhAc9aeumobrgE6Jw4IbFZmrYsTL0jgFWKPT4WZoOTgYsfwjoTtCO,iv:FYyUktTdepN59yYlXQvzbXDnXxIaCVJgkbG2zbfMJ7E=,tag:+Xxi7YzH01Y9UoVZtrTy8g==,type:str]
secret_kubelet_provider_id_okenode2: ENC[AES256_GCM,data:qMn2OrjkJFr6xEMcv8S55aQAqcK9G1zBPWPx8qqOSl7q3y1nD8XnCAaq4J8Ph5617NIM+BWPzMR02S6qMFrkEYa4hd39op3TbtIO4F6RKW/325RZt/zzkZyd,iv:XCOo5Uca7e3cVtOAatRNh4RxetnkCEmg7Dv0L8Wkh2E=,tag:pWVPzx24J+93M0JZhTPZcA==,type:str]
secret_kubelet_provider_id_okenode3: ENC[AES256_GCM,data:6EYJs0i8a9GIkFwFTSKKzOkVURmHu14/8kYUbgJ5tWJ/zA2zMEWnbZyA8LLW1FMV5pWNlN+aU+xKN60YyJ0qG8XGxEqZnSBJ6PzNI88MTvQ3zOf17OV0NiO8,iv:4S02e/KbgZUHN2YoGi5S6MLMsNPdtaKaXZthWwuz3AM=,tag:JtVX2bRnDw6zdS7QpBX9pQ==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNVpVZXZ1d0FtcUtEUnRq
            UDlnSXIxRlF5NGRNNDJ3QTQ2WGQ5bFBuS0U0CmZlMGFrOUhmVkkxTjRyOUE4bnpp
            MXovVE9VRDdhdjNOcnlGYk5TUWp1UUUKLS0tIDhDaGVqV1V0UjE0VU5XaGdHUWtJ
            K3k1dXd2ekhVbFc4SEpIVytlNVBCcTAKxWaqTFm63Ht4WfA72KvPOVp0aVYifc4n
            WQI0NVfaB17cFuODFZEWiY1uL5u5tBz+efut8hZORVFocH3xVsTRxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-29T06:23:55Z"
    mac: ENC[AES256_GCM,data:COUISAuZvP3Qku2kD26MLtXSDjo3CtB8q701UXE4IgnvIF5koBj0XrImg+E9HepC78xL8+t17gf5feg24O/WiVJ1yvKnzkIR8gTwTMWq+uPqWrjjRf28lz/+mF35bEYwAccZHnGe5hFRH/nZG09pAp6SI0xbyPL9Ux43dVm0ZOw=,iv:nVKbT0QcH9aISEt33hZlwyXT80VJ/H2AKGYZYbs4V8E=,tag:xkcm/CDl6nJjA9pohns2rg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
