---
- name: Install PostgreSQL via docker
  docker_container:
    name: "{{ postgres_container_name }}"
    image: "{{ postgres_image }}"
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "{{ postgres_port }}:5432"
    env:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_DB: "{{ postgres_db }}"
    volumes:
      - "{{ postgres_data_dir }}:/var/lib/postgresql/data"
  register: docker_postgres
