---
- name: Make sudo no password for wheel group
  become: true
  community.general.sudoers:
    name: sudo group no password
    commands: ALL
    group: wheel
    nopassword: true
    state: present
    validation: required
