---
- name: Load kubelet secrets
  become: true
  ansible.builtin.set_fact:
    _kubelet_secrets: "{{ lookup('community.sops.sops', '../secrets/secrets.enc.yaml') | from_yaml }}"

- name: Set kubelet secrets
  ansible.builtin.set_fact:
    secret_kubelet_provider_id_okenode1: "{{ _kubelet_secrets.secret_kubelet_provider_id_okenode1 }}"
    secret_kubelet_provider_id_okenode2: "{{ _kubelet_secrets.secret_kubelet_provider_id_okenode2 }}"
    secret_kubelet_provider_id_okenode3: "{{ _kubelet_secrets.secret_kubelet_provider_id_okenode3 }}"

- name: Insert ExecStartPost to enable swap after oke bootstrap
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/oci-oke-node-bootstrap.service
    insertafter: "^ExecStart=/usr/bin/oke bootstrap"
    line: "ExecStartPost=/usr/sbin/swapon /swapfile"
    state: present

- name: Set OKE_EXTRA_ARGS in /etc/oke/oke.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/oke/oke.conf
    regexp: "^OKE_EXTRA_ARGS=.*"
    line: 'OKE_EXTRA_ARGS="--kubelet-user-preferred-args ''--config /etc/kubernetes/kubelet-config-customed.json''"'

- name: Ensure kubelet config file
  become: true
  ansible.builtin.template:
    src: kubelet-config.json.j2
    dest: /etc/kubernetes/kubelet-config-customed.json
    owner: root
    group: root
    mode: "0644"
  notify: Print Reboot Required

- name: Delete kubelet secrets
  ansible.builtin.set_fact:
    _kubelet_secrets: {}
    secret_kubelet_provider_id_okenode1: ""
    secret_kubelet_provider_id_okenode2: ""
    secret_kubelet_provider_id_okenode3: ""
