---
- name: Make journal directory
  become: true
  ansible.builtin.file:
    path: /var/log/journal
    state: directory
    mode: "2755"
    owner: root
    group: systemd-journal
  notify:
    - Restart journald
