---
- name: Install NFS server packages
  become: true
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present

- name: Open NFS ports in the firewall
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 2049
    jump: ACCEPT
    action: insert
    state: present

- name: Create export directory
  become: true
  ansible.builtin.file:
    path: /srv/nfs
    state: directory
    mode: '0755'

- name: Configure exports
  become: true
  notify: Restart NFS service
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "/srv/nfs 10.0.10.0/24(rw,sync,no_subtree_check,no_root_squash)"
    create: true
    owner: root
    group: root
    mode: '0644'
