- name: Ensure PermitRootLogin is set to no
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin\s+.*'
    line: "PermitRootLogin no"
    state: present
    create: false
  notify: Restart sshd
