---
- name: Open http port
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
    action: insert
    state: present

- name: Open https port
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
    action: insert
    state: present
